### ISSUE TITLE
terminal background color is white and prompline vim plugin.

### ISSUE THREAD

**Issue by MethylatorX** [electro7/dotfiles#2]
unlike the one in your screenshot after applying all settings the terminal background color is white
and there are other issues with vim regarding the promptline plugin.

**Comment by kuemmel** [comment]
I'm having trouble getting the fonts to work, so I can't verify, but I think that's because there are hardcoded paths in ~/.Xresources. Just change line 24 from "/home/electro7" to "/home/_yourHomeFolder_".

(edit: Yup, that was it. My Powerline/fonts work inside urxvt(but not in lemon bar :( ). 
edit2: Now it works, it seems that calling xset too soon didn't work out, I just executed the xset commands (found in .xsession) inside the .i3/config.)
