### ISSUE TITLE
Bar was ommited on laptop monitor

### ISSUE THREAD

**Issue by justintv90** [electro7/dotfiles#3]
Lemonbar was cut by haft on laptop monitor, and show full stuff when change to external monitor. What can i do to make it show full stuff on laptop monitor, please help me ?

**Comment by kuemmel** [comment]
Does the rest work(fonts, for example, can you see the powerline-fonts)? I had that on very small monitors or when the xorg config wasn't right(like being set to 800x600 instead of the native resolution). I'd try making a small script and calling xrandr. Maybe just adding
`exec xrandr --auto`
to the i3/config might cut it.
